### ISSUE TITLE
UKBB-Pan-ancestry summary statistics is hg19 or hg38 based?

### ISSUE THREAD

**Issue by Shicheng-Guo** [atgu/ukbb_pan_ancestry#21]
Dear Pan-UKB team: 

I am wondering the summary statistics from the follow excel is hg19 or hg38 based?

https://docs.google.com/spreadsheets/d/1AeeADtT0U1AukliiNyiVzVRdLYPkTbruQSk38DeutU8/edit#gid=30994804

Thanks. 

Shicheng

**Comment by armartin** [comment]
Hello! 

These are on hg19. 

All the best,

Alicia
