### ISSUE TITLE
gnomad_lof/R/constants.R is missing

### ISSUE THREAD

**Issue by Shicheng-Guo** [atgu/ukbb_pan_ancestry#22]
Hi Konrad, 

I cannot find this `constants.R` script. Would you mind share it with me. Thanks. 

`source('~/gnomad_lof/R/constants.R')`

Shicheng

**Comment by mkanai** [comment]
Hi,

You can
```
source('https://raw.githubusercontent.com/macarthur-lab/gnomad_lof/master/R/constants.R')
```

Thanks!
Masa
