### ISSUE TITLE
High AC (low MAC) variants should be filtered

### ISSUE THREAD

**Issue by konradjk** [atgu/ukbb_pan_ancestry#4]
We applied a min AC of 20, but not min MAC. We should apply a variant filter, or at least filter the statistics as part of sumstats QC

**Comment by mkanai** [comment]
I think if we do sumstats QC, it should happen before meta-analysis because it could change which variants to include from each population

**Comment by konradjk** [comment]
Now taken care of in https://github.com/atgu/ukbb_pan_ancestry/blob/31edc35ab1d714a6a90e528f351e228fd3033b6b/load_all_results.py#L35
