### ISSUE TITLE
Document phecodes on wiki

### ISSUE THREAD

**Issue by konradjk** [atgu/ukbb_pan_ancestry#7]
Short description and link to this file: https://github.com/atgu/ukbb_pan_ancestry/blob/master/data/UKB_Phecode_v1.2b1_ICD_Mapping.txt

**Comment by mkanai** [comment]
Added [here](https://github.com/atgu/ukbb_pan_ancestry/wiki/QC/5a54c3cfa8684b36d37056bfa260b2547c3be6a7)
