### ISSUE TITLE
Using with local Pan ukbb data

### ISSUE THREAD

**Issue by jerome-f** [atgu/ukbb_pan_ancestry#72]
Hi,

I am trying to use this package on the hail tables downloaded from panukbb. Some of the file path reference are still pointing to non-public buckets. 
```
__author__ = 'Rahul Gupta'

import hail as hl
from ukbb_common.resources.generic import PHENO_KEY_FIELDS


def get_h2_flat_file():
    return 'gs://ukb-diverse-pops/rg-h2-tables/h2_estimates_all_flat_211101.tsv'


def get_h2_ht():
    return 'gs://ukb-diverse-pops/rg-h2-tables/ht/h2_estimates_all.ht'

```

For instance the bucket is called by `load_final_sumstats_mt()` and I dont seem to have access to these files 

`AccessDeniedException: 403 xxxxx does not have storage.objects.list access to the Google Cloud Storage bucket.`

**Comment by konradjk** [comment]
These have been recently moved, and the paths have been updated in the master branch: https://github.com/atgu/ukbb_pan_ancestry/blob/master/heritability/import_heritability.py#L8
